main: fr.birdo.bedwarsplugin.BedwarsPlugin

name: BedwarsPlugin

description: Bedwars bukkit plugin.

author: Birdo770

version: 1.0

commands:
  bedwars:
    description: Plugin command
    aliases: bw